apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    environment: sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: stable
    path: manifests
    directory:
      include: install.yaml
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
